apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: secureflow
  labels:
    app: auth-service
    team: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        team: secureflow
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "auth-service"
        vault.hashicorp.com/agent-inject-secret-config: "secureflow/data/auth-service"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secureflow/data/auth-service" -}}
          export DB_HOST="{{ .Data.data.db_host }}"
          export DB_NAME="{{ .Data.data.db_name }}"
          export DB_PASSWORD="{{ .Data.data.db_password }}"
          export DB_USER="{{ .Data.data.db_user }}"
          export JWT_SECRET="{{ .Data.data.jwt_secret }}"
          {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: auth-service
      containers:
        - name: auth-service
          image: amdari-project02-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
